baseURL = "https://fohlen.dev"
languageCode = "en-us"
title = "Lennard Berger's blog"
theme = "yinyang"
DefaultContentLanguage = "en"

[services]
  [services.googleAnalytics]
    id = ""

[markup.goldmark.renderer]
unsafe = true

[params]
description = "A Cognitive Scientist's blog"
disqus = ""
headTitle = "Lennard Berger's blog"
mainSections = ["posts"]
postHeaderContent = ""
lazyImage = true
extraCSSFiles = ["css/custom.css"]
extraHead = '''<meta name="google-site-verification" content="nxpWrXt97X-soIBX-zibrfoR5k3EpoomKitRnQRLh70" />
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js"></script>
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js" onload="renderMathInElement(document.body,{delimiters:[{left:'$$',right:'$$',display:true},{left:'$',right:'$',display:false}]});"></script>'''

[params.author]
homepage = "https://github.com/Fohlen"
name = "Lennard Berger"

[[params.socials]]
name = "RSS"
link = "/index.xml"

[[params.socials]]
name = "About"
link = "/about/"

[[params.socials]]
name = "GitHub"
link = "https://github.com/Fohlen"
