[project]
name = "testing-linear-regression-empirically"
version = "0.1.0"
description = "Testing whether ordinary least squares regression empirically holds up its assumptions"
requires-python = ">=3.10"
dependencies = [
    "jupyterlab~=4.3.0",
    "numpy~=2.1.2",
    "scipy~=1.14.1",
    "scikit-learn~=1.5.2",
    "matplotlib~=3.9.2",
    "seaborn~=0.13.2",
    "tqdm~=4.66.6",
]
