[project]
name = "vector-distances-rust"
version = "0.1.0"
description = "An empirical look at the distribution of cosine similarity in GloVe and fastText word embeddings"
requires-python = ">=3.14"
dependencies = [
    "jupyterlab>=4.3,<5",
    "matplotlib>=3.10",
    "more-itertools>=10.2",
    "numpy>=2.2.4",
]

[project.optional-dependencies]
scripts = [
    "fasttext-wheel>=0.9.2",
    "scipy>=1.16",
    "tqdm>=4.66",
]
