[project]
name = "missing-spacy-benchmark"
version = "0.1.0"
description = "Evaluation of spaCy base models (tok2vec vs transformer) on the MTEB benchmark"
requires-python = ">=3.10"
dependencies = [
    "jupyterlab~=4.0.6",
    "pandas~=2.1.1",
    "matplotlib~=3.8.0",
    "seaborn~=0.12.2",
]

[project.optional-dependencies]
scripts = [
    "mteb[beir]~=1.1.0",
    "spacy[apple,transformers]~=3.6.1",
]
